version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    container_name: backend
    restart: always
    depends_on:
      - nginx
    environment:
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=172.20.227.241  
      - DB_PORT=3306
      - DB_DATABASE=grupo1_2425
      - DB_USERNAME=grupo1_2425
      - DB_PASSWORD=FeGh-[69z_8)@ktC  
    volumes:
      - ./backend:/var/www/html
    networks:
      - app_network

  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app_network

networks:
  app_network:
