version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=172.20.227.241
      - DB_PORT=3306
      - DB_DATABASE=grupo1_2425
      - DB_USERNAME=grupo1_2425
      - DB_PASSWORD=FeGh-[69z_8)@ktC
    depends_on:
      - database
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/var/www/frontend/dist
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  database: 
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
